### ISSUE TITLE
ItemsAdder integration for menu buttons doesn't appear to work

### ISSUE THREAD

**Issue by VergilPrime** [HibiscusMC/HMCColor#21]
Menu buttons don't render as the proper item and model ID when using "itemsadderItem" in config.yml

Configuration when using ItemsAdder:
![image](https://cdn.discordapp.com/attachments/1015755231751045200/1131997272427737208/image.png)
/iaget hmccosmetics:paintbrush works and gives me the item, so the issue doesn't appear to be with my IA configuration or copying files from HMCCosmetics wrong.

This configuration seems to work fine]
![image](https://github.com/HibiscusMC/HMCColor/assets/1651211/ad5fe6b8-28a5-4098-b9c2-8e76bdd84d1e)

This seems to confirm that using ItemsAdder configured items with "itemsadderItem" here doesn't work.

**Comment by Boy0000** [comment]
fixed in 0.8
