### ISSUE TITLE
[SUGGESTION] Adding support for Dyeing More items

### ISSUE THREAD

**Issue by MarkinhosMLP** [HibiscusMC/HMCColor#6]
Firework stars can also be dyed, but they dont use display:Color, they use Explosion:Colors instead, and they can even support 2 different colors (they will merge together, so it is not recommended)
Filled maps CAN BE DYED TOO!!! but with display:MapColor
worth mentioning, the map will not change the holding model, but it is good for display like cosmetic things, (since it is an empty filled map you can use in itemframes) and stuff like that

Example commands
/give @p leather_horse_armor{display:{color:51967}} 1
/give @p firework_star{Explosion:{Colors:[I;51967],Type:0b}} 1
/give @p minecraft:filled_map{display:{MapColor:51967}}

for the two colors
/give @p firework_star{Explosion:{Colors:[I;51967,6947071],Type:0b}} 1

**Comment by Boy0000** [comment]
Same dev. I can add map but due to how fireworkstar has 2 colors not sure how well it will work. Will do some checks internally and see
